# Generated by Django 4.1.4 on 2022-12-25 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIRequestTracker",
            fields=[
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("request_limit", models.PositiveIntegerField(default=0)),
                ("current_request_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "news_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("date_created", models.DateTimeField(null=True)),
                ("title", models.CharField(max_length=300)),
                (
                    "story_type",
                    models.CharField(
                        choices=[
                            ("job", "job"),
                            ("story", "story"),
                            ("comment", "comment"),
                            ("poll", "poll"),
                            ("pollopt", "pollopt"),
                            ("", ""),
                        ],
                        default="",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("url", models.CharField(max_length=300, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
