# Generated by Django 4.1.4 on 2022-12-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chainstack_api", "0004_newsitem_news_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="news_detail",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
