# Generated by Django 4.1.4 on 2022-12-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chainstack_api", "0006_errorlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorlog",
            name="date_created",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="log",
            field=models.TextField(editable=False, null=True),
        ),
    ]
