# Generated by Django 4.1.4 on 2022-12-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chainstack_api", "0007_errorlog_date_created_alter_errorlog_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorlog",
            name="log",
            field=models.TextField(null=True),
        ),
    ]
