# Generated by Django 4.1.4 on 2022-12-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chainstack_api", "0008_alter_errorlog_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorlog",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
